spring.application.name=digitalwallet

spring.datasource.url=jdbc:h2:mem:natwestdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2

natwest.clientId=${NATWEST_CLIENT_ID}
natwest.clientSecret=${NATWEST_CLIENT_SECRET}
natwest.redirectUri=${NATWEST_REDIRECT_URI}
natwest.psuUsername=${NATWEST_PSU_USERNAME}

natwest.baseApi=${NATWEST_BASE_API}
natwest.baseOb=${NATWEST_BASE_OB}


